### ISSUE TITLE
[metal-drag-drop] Draggable elements are not clickable

### ISSUE THREAD

**Issue by p2kmgcl** [metal/metal-plugins#111]
Once you set a draggable element with metal-drag-drop, there is no way to make it clickable without using a handler.

**Comment by diegonvs** [comment]
Could you give me more details @p2kmgcl? Are you needing a new listener like `Drag.Events.INTERACT`, that will be emitted when have any interactions in sources elements before a START for example?

**Comment by p2kmgcl** [comment]
When an item is added as metal-drag-drop source, metal captures mousedown event, and for that reason links and buttons stop working.

In this case:

![screenshot_2019-01-15_16-29-27](https://user-images.githubusercontent.com/800645/51190580-d9f68c80-18e2-11e9-93f6-ea674e20fee3.png)

We needed to add a drag handler, because otherwise the item is not clickable anymore.

**Comment by diegonvs** [comment]
This behaviour occurs when `useShim` option isn't not setted to false. When you don’t pass `false` for this option, a DragShim is enabled for your Drag instance. basically this shim is used to attach events of Drag move and end like `mousemove` and `mouseup` to a shim element that can be placed above the document do hear these events. This functionality is important for dragging nodes over iframes. If `false`, these events of Drag move and end will be attached in the document :slightly_smiling_face:
