### ISSUE TITLE
[metal-drag-drop] Provide some CSS class to the element being dragged

### ISSUE THREAD

**Issue by p2kmgcl** [metal/metal-plugins#112]
![image](https://user-images.githubusercontent.com/800645/50217129-243e2980-0388-11e9-93da-8b577bb28928.png)

As a `targetOver` is given to a drop target, and a `dragging` is given to the drag placeholder, an extra `dragged` (or something else) class could be given to the source element being dragged, so it can be identified and/or styled during the drag process.

**Comment by diegonvs** [comment]
Hey @p2kmgcl, once `targetOverClass` and `draggingClass` receives a string to add classes, you could use like this example:

```javascript
var dragDrop = new metal.DragDrop({
			dragPlaceholder: metal.Drag.Placeholder.CLONE,
			handles: '.handle',
			sources: '.box',
			targets: '.target',
			targetOverClass: 'over over2',
			draggingClass: 'dragx'
});```

Note that when you are defining a `targetOverClass` or `draggingClass` the default `targetOver` or `dragging` class will not be added automatically. You can add manually like `draggingClass: 'dragging dragx'`  or `targetOverClass: 'targetOver over over2'`, if you want add a existing default class, for example :)

**Comment by p2kmgcl** [comment]
Hi @diegonvs, let me try to clarify this. While dragging some element, you have three elements:

- A target element where you are dragging over, which can be customized with targetOverClass.
- A dragging element, which only exits while dragging, and which can be customized with draggingClass.
- And a source element, which is the element where the drag started. This element cannot be customized, and this is the option I would like to have included with a `dragSourceClass` or so option.

**Comment by diegonvs** [comment]
Thanks for clarification @p2kmgcl! I'll take a look on this!
