### ISSUE TITLE
Move metal-useragent to this repo

### ISSUE THREAD

**Issue by zenorocha** [metal/metal-plugins#23]
Is there any reason why https://github.com/metal/metal-useragent isn't here?

**Comment by jbalsas** [comment]
No reason, we just haven't gotten to it yet. To move a plugin here means we've reviewed it, applied the common guidelines and cleared any standing PRs and issues in the old repo. 

We've been doing more or less one every 2 weeks, being [`metal-position`](https://github.com/metal/metal-plugins/pull/20) the last one to be included and prioritizing the ones that are requiring active development by our teams.

**Comment by diegonvs** [comment]
I think we can close this issue, since this package has already been imported. 
https://github.com/metal/metal-plugins/tree/master/packages/metal-useragent
