### ISSUE TITLE
[metal-drag-drop] Placeholder is added to the target list

### ISSUE THREAD

**Issue by sandrodw3** [metal/metal-plugins#97]
I am using metal-drag-drop in a a list of divs that I want to reorder, so in this particular case, sources are also targets. 

As I am using Drag.Placeholder.CLONE as placeholder, at the moment of start dragging, this placeholder is added to the target list, and it sometimes causes problems because the placeholder targets itself.

Would it be possible to prevent the placeholder to be added to the target list in this particular case that sources are also targets?

Thanks in advance!

**Comment by diegonvs** [comment]
Hello @sandrodw3, if possible, could you explain using an example?

**Comment by sandrodw3** [comment]
Hey @diegonvs! Sorry for the wait. I show you an example:

![image](https://user-images.githubusercontent.com/2444936/47000579-7a8cb300-d120-11e8-9e99-568e621a9b64.png)

I want to move these items through the columns. I can drop them on another item or between two of them. So in this case, when I define the metal drag and drop instance, I select these items as both sources and targets. 

As you can see, in this example I am moving 'Page 1', and a clone of it is created to drag. The possible targets in this case should be 'My home Page', 'Page 2' and 'Page 3'. Nevertheless, the 'Page 1' clone (the one that I pointed with a red arrow) is also added to the targets list, and it sometimes causes inappropiate behavior when I drop the items.

I hope to have explained it better this time. Thank you!!

**Comment by diegonvs** [comment]
Hey @sandrodw3, sorry for the delay. I'm working on this right now. :)
